### ISSUE TITLE
market-info 插件使用问题

### ISSUE THREAD

**Issue by sheep2007** [koishijs/koishi-plugin-market-info#7]
目前最新版（2.0.0） market-info 插件启动后会有警告

![image](https://github.com/koishijs/koishi-plugin-market-info/assets/122354009/6f0078b9-01ad-4623-b935-ea78e6a04f8a)

并且指令“merket”没有了

（旧版本）

![image](https://github.com/koishijs/koishi-plugin-market-info/assets/122354009/3689ac39-ff72-45f7-9f95-694cc9a1d3af)

（最新版）

![image](https://github.com/koishijs/koishi-plugin-market-info/assets/122354009/8fca1562-51af-42a9-b6a8-cefae66fd624)

订阅的平台频道也没有推送更新

![image](https://github.com/koishijs/koishi-plugin-market-info/assets/122354009/6d0182c7-f66b-4610-b6b6-5cabad282fab)

**Comment by shigma** [comment]
已复现，正在修复。

**Comment by shigma** [comment]
请使用最新版本再次尝试。
